### ISSUE TITLE
[FIXED] Beta compatibility

### ISSUE THREAD

**Issue by sergeevabc** [tuteken/Keypirinha-Plugin-Ditto#1]
Dear Tuteken,
Is this plugin compatible with [Ditto Beta][1]? 

[1]: http://ditto-cp.sourceforge.net/beta/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by tuteken** [comment]
Hello,

I have not done any testing with the beta version of Ditto.  The plugin connects directly to the Ditto database, so as long as that does not change there should not be any problems.

**Comment by sergeevabc** [comment]
Right, I confirm it is compatible with Ditto Beta (3.21.122.0 to date).

Consider providing *.keypirinha-package [like this][1].

Also I’m confused with the following part of configuration (since it contains path unknown to me):
```
#F:\Sync\Bag\Applications\Ditto\Ditto.dbalways_suggest = no
```

[1]: https://github.com/ueffel/Keypirinha-Plugin-Kill/releases
