### ISSUE TITLE
Default database file setting to default Ditto database file path

### ISSUE THREAD

**Issue by ueffel** [tuteken/Keypirinha-Plugin-Ditto#2]
It would be nice if the ditto package would work out of the box with a default ditto installation without any configuration. 
My suggestion would be to set the default database path to the default path of the ditto database with the following code changes:

`ditto.py:`
```python
...
import os
...
DEFAULT_DATABASE_FILE = "{}/Ditto/Ditto.db".format(os.environ.get('APPDATA'))
```

`ditto.ini:`
```ini
...
[main]
...
#database_file = ${env:APPDATA}/Ditto/Ditto.db
```

Think about it :)

**Comment by polyvertex** [comment]
If I may and since environment vars are not always reliable, something along those lines would be safer and slightly more pedantic (untested so there might be a typo):

`ditto.py`:

```python
import keypirinha_wintypes as kpwt
import os.path

DEFAULT_DATABASE_FILE = os.path.join(kpwt.get_known_folder_path(kpwt.FOLDERID.RoamingAppData),
                                     "Ditto", "Ditto.db")
```

`ditto.ini`:

```ini
[main]
#database_file = ${var:KNOWNFOLDER_ROAMINGAPPDATA}
```

**Comment by tuteken** [comment]
Thank you for your interest in this project.  I have stopped using Keypirinha and will be archiving this repository.

**Comment by tuteken** [comment]
Thank you for your interest in this project.  I have stopped using Keypirinha and will be archiving this repository.
