### ISSUE TITLE
Can the README be updated to include more information on how to use and configure this plugin? 

### ISSUE THREAD

**Issue by ghost** [tuteken/Keypirinha-Plugin-Ditto#3]
Please excuse all following noob questions.

Fortunately, I installed this through PackageControl so at least a blank ini was placed in the correct location but I'm not sure about the python file. Where does this go and what's it for? How is it used? 

I admit it took me a bit to figure out that the installed blank ini needed to filled in with the info in this repository because I didn't check it. (Did I mention the noob thing?) The README instructions just say to add the path to the database, which I also needed to figure out where that was though it didn't take long. I'm just saying, a little more info would be helpful. =]

For instance:

If installing through PackageControl:
Enter the full path to the database in the user version of ditto.ini 
        type "Configure Package: Ditto" into Keypirinha to open the configuration files 
		
This will open the blank ditto.ini file so that the ditto.ini info from this repository can be pasted into it. Then the path %AppData%\Ditto\Ditto.db (or wherever your database file is located) can be placed into it. Search for 'database' (CTRL+F) or just look under [main] ... (uncomment first by removing the # symbol) "database_file = <path>".

If not installing via PackageControl (aka manually):
		Copy the ditto.ini from this repository & place into: %APPDATA%\Keypirinha\User\ditto.ini
		Follow the above instructions to enter the full path to the database in the user version of ditto.ini.

Add info regrading the Python file.

Maybe add usage info. For instance, what does this mean?
Should the plugin always suggest candidates if their content
matches the search terms?
* Enabling this option saves you some keystrokes since you do not have to
search then select the prefix item first, before being able to
choose the application you want to activate.

The fact that it can be installed through PackageControl could also be added. Others include something like this:
@ueffel wrote PackageControl, a package manager that eases installation of third-party packages. It can be installed manually or through Keypirinha's command line.
https://github.com/ueffel/Keypirinha-PackageControl

Thanks!

**Comment by tuteken** [comment]
Thank you for your interest in this project.  I have stopped using Keypirinha and will be archiving this repository.
