### ISSUE TITLE
Plugin corrupted my database?

### ISSUE THREAD

**Issue by galantra** [tuteken/Keypirinha-Plugin-Ditto#5]
I installed the plugin today and tried it out. Immediately afterwards, I couldn't search my clips in the ditto application (outside Keypirinha). I could still see the list of clips, but as soon as I entered a letter in the search field, the clip list became empty.

Later, I updated my (portable, BTW) version of Ditto. It said that there is sth wrong with the ditto.db file. It renamed it to Ditto_BAD.db and created a new db file.

**Comment by tuteken** [comment]
Thank you for letting me know.  I'm sorry to hear that my plugin corrupted your Ditto database.  I haven't been using this plugin for some time, so it must have fallen behind Ditto and changes to the SQLite database schema.  I'm going to mark this plug deprecated.

**Comment by galantra** [comment]
Thanks for your response! My Ditto db was not important, BTW. So don't worry.
